aws:
  region: "${AWS_REGION}"
  dynamodb:
    endpoint: "${AWS_DYNAMODB_ENDPOINT:http://localhost:8000}"
  jwt:
    secretName: "${AWS_JWT_SECRET_NAME}"
  sqs:
    listener:
      secretName: "${AWS_SQS_LISTENER_SECRET_NAME}"

logging:
  level:
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG
    org.springframework.transaction.interceptor: DEBUG
    org.springframework.transaction.reactive: DEBUG
    org.springframework.transaction: DEBUG
    io.r2dbc.h2: DEBUG
