spring:
  application:
    name: "crediya-ms-reports"
  config:
    import: "optional:classpath:local.properties"
  devtools:
    add-properties: false
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"

server:
  port: "${PORT:8082}"

management:
  endpoints:
    web:
      base-path: "/api/v1/reports/actuator"
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS}"

springdoc:
  api-docs:
    path: "/api/v1/reports/api-docs"
  swagger-ui:
    path: "/api/v1/reports/swagger-ui.html"