aws:
  region: "${AWS_SQS_REGION}"
  dynamodb:
    endpoint: "${AWS_DYNAMODB_ENDPOINT:http://localhost:8000}"

entrypoint:
  sqs:
    region: "${AWS_SQS_REGION}"
    queueUrl: "${AWS_SQS_QUEUE_URL}"
    loanApprovedEventsQueueQueueName: "${AWS_SQS_LOAN_APPROVED_EVENTS_QUEUE_NAME}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1

application:
  security:
    jwt:
      expiration: 7200000
      secret-key: "${JWT_SECRET_KEY}"

logging:
  level:
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG
    org.springframework.transaction.interceptor: DEBUG
    org.springframework.transaction.reactive: DEBUG
    org.springframework.transaction: DEBUG
    io.r2dbc.h2: DEBUG
