spring:
  application:
    name: "crediya-ms-reports"
  config:
    import: "optional:classpath:local.properties"
  devtools:
    add-properties: false
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
server:
  port: "${PORT:8081}"
